CREATE TABLE Users
(
	UserID VARCHAR(50) NOT NULL,
	SellerRating INT NOT NULL,
	BidRating INT NOT NULL,
	Location VARCHAR (100),
	Country VARCHAR (50),
	
	PRIMARY KEY(UserID)		
);

CREATE TABLE Item
( 
	ItemID INT(10) NOT NULL,
	Seller VARCHAR(50) NOT NULL, 	
	Name VARCHAR(100) NOT NULL,	
	Currently DECIMAL(8,2) NOT NULL,
	First_Bid DECIMAL(8,2) NOT NULL,
	Bid_Num INT NOT NULL, 
	Buy_Price DECIMAL(8,2),
	Location VARCHAR (100) NOT NULL,
	Country VARCHAR (50) NOT NULL,
	Latitude VARCHAR(11),
	Longitude VARCHAR(11),
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	Description VARCHAR(4000),

	PRIMARY KEY(ItemID),
	FOREIGN KEY (Seller) REFERENCES Users(UserID)
);

CREATE TABLE ItemCategory
(
 ItemID   INT(10) NOT NULL,
 Category VARCHAR(100) NOT NULL,
 
 FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);



CREATE TABLE Bids
(
	BidID INT(10) NOT NULL,
	Bidder VARCHAR(50) NOT NULL,
	ItemID INT(10) NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8,2) NOT NULL,

	PRIMARY KEY(BidID),
	FOREIGN KEY (Bidder) REFERENCES Users(UserID),
	FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);
