LOAD DATA LOCAL INFILE "Users.del" INTO TABLE Users FIELDS TERMINATED BY "|*|";
LOAD DATA LOCAL INFILE "Item.del" INTO TABLE Item FIELDS TERMINATED BY "|*|";
LOAD DATA LOCAL INFILE "ItemCategory.del" INTO TABLE ItemCategory FIELDS TERMINATED BY "|*|";
LOAD DATA LOCAL INFILE "Bids.del" INTO TABLE Bids FIELDS TERMINATED BY "|*|";