LOAD DATA LOCAL INFILE "Users.csv" INTO TABLE Users FIELDS TERMINATED BY "|*|";
LOAD DATA LOCAL INFILE "Item.csv" INTO TABLE Item FIELDS TERMINATED BY "|*|";
LOAD DATA LOCAL INFILE "ItemCategory.csv" INTO TABLE ItemCategory FIELDS TERMINATED BY "|*|";
LOAD DATA LOCAL INFILE "Bids.csv" INTO TABLE Bids FIELDS TERMINATED BY "|*|";